# Lab 02: ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: fis-workshop
data:
  application.properties: |
    # OpenShift Properties
    route.xml.period=30s
    route.dsl.period=45s

    # Messages
    route.xml.body=(ConfigMap) Generated Number
    route.dsl.body=(ConfigMap) Hi World!

    # ActiveMQ Configuration
    # The name of the service hosting the ActiveMQ broker or message gateway
    # Can be customized using the 'ACTIVEMQ_SERVICE_NAME' variable to use a different broker.
    activemq.service.name=activemq

    # The following properties can be customized using the 'ACTIVEMQ_SERVICE_HOST' and 'ACTIVEMQ_SERVICE_PORT' environment variables.
    # This is indeed done automatically by Kubernetes when the application is deployed in a namespace containing an instance of ActiveMQ named 'activemq'.
    # The service defaults to localhost. You need to change these properties for development purposes only.
    # activemq.service.host=broker-amq-tcp.fis-workshop.svc
    # activemq.service.host=172.17.0.3
    activemq.service.host=broker-amq-tcp
    activemq.service.port=61616

    # The following property binds all previous configurations together
    # activemq.broker.url=tcp://${${activemq.service.name}.service.host}:${${activemq.service.name}.service.port}
    activemq.broker.url=tcp://broker-amq-tcp:61616

    # Set the number of concurrent consumers for the ActiveMQ ('ACTIVEMQ_CONCURRENT_CONSUMERS')
    activemq.concurrent.consumers=10

    # Set the number of connections created by the connection pool ('ACTIVEMQ_POOL_MAX_CONNECTIONS')
    activemq.pool.max.connections=10

    # If required, you can set the broker credentials using environment variables.
    # Variable names are 'ACTIVEMQ_BROKER_USERNAME' and 'ACTIVEMQ_BROKER_PASSWORD'.
    # The following credentials are valid for Arquillian tests (see 'src/test/resources/amq.json').
    activemq.broker.username=admin
    activemq.broker.password=admin
    
    # AMQP Broker
    # amqp.broker.url = amqps://messaging-enmasse.192.168.42.59.nip.io:443?sslEnabled=true&transport.trustAll=true&transport.verifyHost=false
    amqp.broker.url = amqp://messaging.enmasse.svc:5672
    amqp.broker.username = developer
    amqp.broker.password = developer
